# This is a basic workflow to help you get started with Actions

name: build busybox index.cgi on win64

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # REMOVED

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl -LO https://gist.github.com/esec/fa6fca76f67320129d4c488975cf6a41/raw/httpd_indexcgi.c -O https://github.com/sourcefrog/natsort/raw/master/strnatcmp.h -O https://github.com/sourcefrog/natsort/raw/master/strnatcmp.c

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          gcc -o index.cgi httpd_indexcgi.c strnatcmp.c
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: index.cgi
